services:
  - type: worker
    name: telegram-media-filter-bot
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    instanceType: starter
    envVars:
      - key: BOT_TOKEN
        fromDatabase: false
      - key: ADMIN_IDS
        fromDatabase: false
